# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\PyCharm\projetos\Projeto_Integrador_6\View\UI\FrmPrincipal2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FrmPrincipal(object):
    def setupUi(self, FrmPrincipal):
        FrmPrincipal.setObjectName("FrmPrincipal")
        FrmPrincipal.setWindowModality(QtCore.Qt.NonModal)
        FrmPrincipal.resize(1049, 555)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\PyCharm\\projetos\\Projeto_Integrador_6\\View\\UI\\../Imagens/FrmIcon_Car.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FrmPrincipal.setWindowIcon(icon)
        FrmPrincipal.setAutoFillBackground(False)
        FrmPrincipal.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.508, y1:0.727, x2:0.505, y2:1, stop:0 rgba(255, 255, 153, 255), stop:1 rgba(255, 255, 255, 255))")
        FrmPrincipal.setIconSize(QtCore.QSize(40, 40))
        self.centralwidget = QtWidgets.QWidget(FrmPrincipal)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 1031, 101))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.btnAlugar = QtWidgets.QPushButton(self.groupBox_2)
        self.btnAlugar.setGeometry(QtCore.QRect(10, 10, 151, 81))
        self.btnAlugar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlugar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnAlugar.setAutoFillBackground(False)
        self.btnAlugar.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"background-color: rgb(20,20,20);\n"
"color:rgb(200,200,200);\n"
"font: 87 12pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{ \n"
"background-color:rgb(0, 0, 0);\n"
"color: rbg(200,200,200)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(0,0,30);\n"
"color:rbg(200,200,200)\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("d:\\PyCharm\\projetos\\Projeto_Integrador_6\\View\\UI\\../../Imagens/Aluguel_veiculo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAlugar.setIcon(icon1)
        self.btnAlugar.setIconSize(QtCore.QSize(40, 40))
        self.btnAlugar.setObjectName("btnAlugar")
        self.btnCliente = QtWidgets.QPushButton(self.groupBox_2)
        self.btnCliente.setGeometry(QtCore.QRect(170, 10, 161, 81))
        self.btnCliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCliente.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"background-color: rgb(20,20,20);\n"
"color:rgb(200,200,200);\n"
"font: 87 12pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{ \n"
"background-color:rgb(0, 0, 0);\n"
"color: rbg(200,200,200)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(0,0,30);\n"
"color:rbg(200,200,200)\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("d:\\PyCharm\\projetos\\Projeto_Integrador_6\\View\\UI\\../../Imagens/Cadastrar_cliente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCliente.setIcon(icon2)
        self.btnCliente.setIconSize(QtCore.QSize(30, 30))
        self.btnCliente.setObjectName("btnCliente")
        self.btnVeiculo = QtWidgets.QPushButton(self.groupBox_2)
        self.btnVeiculo.setGeometry(QtCore.QRect(340, 10, 171, 81))
        self.btnVeiculo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnVeiculo.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"background-color: rgb(20,20,20);\n"
"color:rgb(200,200,200);\n"
"font: 87 12pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{ \n"
"background-color:rgb(0, 0, 0);\n"
"color: rbg(200,200,200)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(0,0,30);\n"
"color:rbg(200,200,200)\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("d:\\PyCharm\\projetos\\Projeto_Integrador_6\\View\\UI\\../../Imagens/Cadastrar_veiculo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVeiculo.setIcon(icon3)
        self.btnVeiculo.setIconSize(QtCore.QSize(40, 40))
        self.btnVeiculo.setObjectName("btnVeiculo")
        self.btnListCliente = QtWidgets.QPushButton(self.groupBox_2)
        self.btnListCliente.setGeometry(QtCore.QRect(520, 10, 171, 81))
        self.btnListCliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnListCliente.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"background-color: rgb(20,20,20);\n"
"color:rgb(200,200,200);\n"
"font: 87 12pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{ \n"
"background-color:rgb(0, 0, 0);\n"
"color: rbg(200,200,200)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(0,0,30);\n"
"color:rbg(200,200,200)\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("d:\\PyCharm\\projetos\\Projeto_Integrador_6\\View\\UI\\../../Imagens/Lista_cliente.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnListCliente.setIcon(icon4)
        self.btnListCliente.setIconSize(QtCore.QSize(30, 30))
        self.btnListCliente.setObjectName("btnListCliente")
        self.btnListVeiculo = QtWidgets.QPushButton(self.groupBox_2)
        self.btnListVeiculo.setGeometry(QtCore.QRect(700, 10, 161, 81))
        self.btnListVeiculo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnListVeiculo.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"background-color: rgb(20,20,20);\n"
"color:rgb(200,200,200);\n"
"font: 87 12pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{ \n"
"background-color:rgb(0, 0, 0);\n"
"color: rbg(200,200,200)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(0,0,30);\n"
"color:rbg(200,200,200)\n"
"}\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("d:\\PyCharm\\projetos\\Projeto_Integrador_6\\View\\UI\\../../Imagens/Lista_Veiculos.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnListVeiculo.setIcon(icon5)
        self.btnListVeiculo.setIconSize(QtCore.QSize(30, 30))
        self.btnListVeiculo.setObjectName("btnListVeiculo")
        self.btnListAluguel = QtWidgets.QPushButton(self.groupBox_2)
        self.btnListAluguel.setGeometry(QtCore.QRect(870, 10, 151, 81))
        self.btnListAluguel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnListAluguel.setStyleSheet("QPushButton{\n"
"border-radius: 5px;\n"
"background-color: rgb(20,20,20);\n"
"color:rgb(200,200,200);\n"
"font: 87 12pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton:hover{ \n"
"background-color:rgb(0, 0, 0);\n"
"color: rbg(200,200,200)\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color:rgb(0,0,30);\n"
"color:rbg(200,200,200)\n"
"}\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("d:\\PyCharm\\projetos\\Projeto_Integrador_6\\View\\UI\\../../Imagens/Lista_aluguel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnListAluguel.setIcon(icon6)
        self.btnListAluguel.setIconSize(QtCore.QSize(30, 30))
        self.btnListAluguel.setObjectName("btnListAluguel")
        self.lbImg = QtWidgets.QLabel(self.centralwidget)
        self.lbImg.setGeometry(QtCore.QRect(100, 130, 801, 351))
        self.lbImg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.lbImg.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.lbImg.setText("")
        self.lbImg.setPixmap(QtGui.QPixmap("d:\\PyCharm\\projetos\\Projeto_Integrador_6\\View\\UI\\../../Imagens/Logo_Meca.jpeg"))
        self.lbImg.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.lbImg.setObjectName("lbImg")
        FrmPrincipal.setCentralWidget(self.centralwidget)
        self.actionCliente = QtWidgets.QAction(FrmPrincipal)
        self.actionCliente.setObjectName("actionCliente")
        self.actionVe_culo = QtWidgets.QAction(FrmPrincipal)
        self.actionVe_culo.setObjectName("actionVe_culo")
        self.actionAlugar = QtWidgets.QAction(FrmPrincipal)
        self.actionAlugar.setObjectName("actionAlugar")
        self.actionCliente_2 = QtWidgets.QAction(FrmPrincipal)
        self.actionCliente_2.setObjectName("actionCliente_2")
        self.actionVe_culos = QtWidgets.QAction(FrmPrincipal)
        self.actionVe_culos.setObjectName("actionVe_culos")
        self.actionAlugueis = QtWidgets.QAction(FrmPrincipal)
        self.actionAlugueis.setObjectName("actionAlugueis")
        self.actionSair = QtWidgets.QAction(FrmPrincipal)
        self.actionSair.setObjectName("actionSair")

        self.retranslateUi(FrmPrincipal)
        QtCore.QMetaObject.connectSlotsByName(FrmPrincipal)

    def retranslateUi(self, FrmPrincipal):
        _translate = QtCore.QCoreApplication.translate
        FrmPrincipal.setWindowTitle(_translate("FrmPrincipal", "Locadora de Veículos"))
        self.btnAlugar.setText(_translate("FrmPrincipal", "Alugar Veículo"))
        self.btnCliente.setText(_translate("FrmPrincipal", "Cadastrar Cliente"))
        self.btnVeiculo.setText(_translate("FrmPrincipal", "Cadastrar Veículo"))
        self.btnListCliente.setText(_translate("FrmPrincipal", "Listar Clientes"))
        self.btnListVeiculo.setText(_translate("FrmPrincipal", "Listar Veículos"))
        self.btnListAluguel.setText(_translate("FrmPrincipal", "Listar Alugueis"))
        self.actionCliente.setText(_translate("FrmPrincipal", "Cliente"))
        self.actionVe_culo.setText(_translate("FrmPrincipal", "Veículo"))
        self.actionAlugar.setText(_translate("FrmPrincipal", "Alugar Veículo"))
        self.actionCliente_2.setText(_translate("FrmPrincipal", "Clientes"))
        self.actionVe_culos.setText(_translate("FrmPrincipal", "Veículos"))
        self.actionAlugueis.setText(_translate("FrmPrincipal", "Alugueis"))
        self.actionSair.setText(_translate("FrmPrincipal", "Sair"))
